AWSTemplateFormatVersion: '2010-09-09'
Description: Networking infrastructure for the blog

Resources:
  BlogVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: blog-vpc
