AWSTemplateFormatVersion: '2010-09-09'
Description: S3 static website hosting for jsywulak.com

Parameters:
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: Existing Route 53 hosted zone ID for jsywulak.com

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jsywulak.com
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Name
          Value: blog-website-bucket

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${WebsiteBucket.Arn}/*'

  WebsiteRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: jsywulak.com
      Type: A
      AliasTarget:
        DNSName: s3-website-us-east-1.amazonaws.com
        HostedZoneId: Z3AQBSTGFYJSTF  # S3 website hosted zone for us-east-1

Outputs:
  WebsiteURL:
    Description: URL of the website
    Value: !Sub 'http://${WebsiteBucket}.s3-website-us-east-1.amazonaws.com'

  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref WebsiteBucket
